services:
   postgres:
      container_name: postgres
      image: postgres
      environment:
         POSTGRES_USER: drasko
         POSTGRES_PASSWORD: password
         PGDATA: /data/postgres
         POSTGRES_DB: pdb
      volumes:
      - postgres:/data/postgres
      ports:
      - 5432:5432
      networks:
      - postgres
      restart: unless-stopped

   pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      environment:
         PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
         PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
         PGADMIN_CONFIG_SERVER_MODE: "False"
      volumes:
      - pgadmin:/var/lib/pgadmin
      ports:
      - 5050:80
      networks:
      - postgres
      restart: unless-stopped
   rabbit:
      image: rabbitmq:3.9.11-management-alpine
      container_name: rabbit
      ports:
      - 5672:5672
      - 15672:15672
      networks:
      - spring

   eureka-server:
      image: asc108/eureka-server:latest
      container_name: eureka-server
      ports:
      - 8761:8761
      environment:
      - SPRING_PROFILES_ACTIVE=docker
      networks:
      - spring
   api-geteway:
      image: asc108/api-gateway:latest
      container_name: api-geteway
      ports:
      - 8084:8084
      environment:
      - SPRING_PROFILES_ACTIVE=docker
      networks:
      - spring
      depends_on:
      - eureka-server
   notification:
      image: asc108/notification:latest
      container_name: notification
      ports:
      - 8083:8083
      environment:
      - SPRING_PROFILES_ACTIVE=docker
      networks:
      - spring
      - postgres
      depends_on:
      - eureka-server
      - postgres
      - rabbit
   order:
      image:  asc108/order:latest
      container_name: order
      ports:
      - 8082:8082
      environment:
      - SPRING_PROFILES_ACTIVE=docker
      networks:
      - spring
      - postgres
      depends_on:
      - eureka-server
      - postgres
   product:
      image: asc108/product:latest
      container_name: product
      ports:
      - 8081:8081
      environment:
      - SPRING_PROFILES_ACTIVE=docker
      networks:
      - spring
      - postgres
      depends_on:
      - eureka-server
      - postgres

   user:
      image: asc108/user:latest
      container_name: user
      ports:
      - 8080:8080
      environment:
      - SPRING_PROFILES_ACTIVE=docker
      networks:
      - spring
      - postgres
      depends_on:
      - eureka-server
      - postgres
      - rabbit
networks:
   postgres:
      driver: bridge
   spring:
      driver: bridge
volumes:
   postgres: null
   pgadmin: null